# Generated by Django 5.2.4 on 2025-08-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='STACCollection',
        ),
        migrations.RemoveField(
            model_name='stacitem',
            name='geojson_file',
        ),
        migrations.RemoveField(
            model_name='stacitem',
            name='tif_file',
        ),
        migrations.CreateModel(
            name='STACAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('roles', models.JSONField(blank=True, null=True)),
                ('asset_file', models.FileField(upload_to='assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.stacitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
